apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: air4life-on-the-edge
spec:
  # --- Predictive Maintenance Integration ---
  # This workflow integrates Copernicus/forecast data via the predictive_maintenance module.
  # When dust storm risk is high, NebulOuS will preemptively trigger cleaning and/or scale resources.
  components:
    - componentName: edge-cleaner
      traits:
        - type: scaler
          properties:
            min: 1
            max: 5
        - type: metrics
          properties:
            cpu: 0.7
    - componentName: predictive-trigger
      # This is a logical component representing the predictive Copernicus workflow.
      # It does not run as a standalone service but acts as a trigger for orchestration.
      traits:
        - type: event-trigger
          properties:
            source: copernicus_forecast
            action: preemptive_cleaning

  parameters:
    - name: SENSOR_POLL_INTERVAL
      value: "10"
    - name: SOILING_THRESHOLD
      value: "0.7"

---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: edge-cleaner
spec:
  type: worker
  properties:
    image: ghcr.io/yourusername/edge-cleaner:latest  # Replace with your actual image
    ports:
      - 8080
    env:
      - name: SENSOR_POLL_INTERVAL
        value: "10"
      - name: SOILING_THRESHOLD
        value: "0.7"
    resources:
      cpu: "2"
      memory: "2Gi"

---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: predictive-trigger
spec:
  type: worker
  properties:
    # This is a placeholder to document the predictive maintenance logic.
    # Real implementation is in /predictive_maintenance/ and integrated via analytics.py and main.py.
    description: |
      This component represents the planned integration of Copernicus/forecast data
      to trigger preemptive cleaning and scaling. See /predictive_maintenance/ for details.
