apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: air4life-edge
spec:
  components:
    - name: edge-cleaner
      type: webservice
      properties:
        image: ghcr.io/yourorg/edge-cleaner:1.4.0  # Fixed: Using the actual image version
        ports:
          - port: 5000
            expose: true
        env:
          - name: FLASK_ENV
            value: production

    - name: predictive-trigger  # Added new component for predictive maintenance
      type: worker
      properties:
        cmd: ["python", "predictive/predictive_trigger.py"]
        env:
          - name: PREDICTIVE_THRESHOLD
            value: "0.7"
          - name: POLL_INTERVAL
            value: "60"
        dependencies:
          - edge-cleaner


