apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: air4life-on-the-edge
spec:
  components:
    - componentName: edge-cleaner
      traits:
        - type: scaler
          properties:
            min: 1
            max: 5
    - componentName: predictive-trigger
      # Logical component for predictive Copernicus workflow.
      traits:
        - type: event-trigger
          properties:
            source: copernicus_forecast
            action: preemptive_cleaning
  parameterValues:
    - name: SENSOR_POLL_INTERVAL
      value: "10"
    - name: SOILING_THRESHOLD
      value: "0.7"

---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: edge-cleaner
spec:
  type: worker
  properties:
    image: ghcr.io/yourusername/edge-cleaner:latest  # Replace with your actual image
    ports:
      - 5000
  env:
    - name: SENSOR_POLL_INTERVAL
      value: "10"
    - name: SOILING_THRESHOLD
      value: "0.7"
  resources:
    cpu: "2"
    memory: "2Gi"

---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: predictive-trigger
spec:
  type: worker
  properties:
    # Placeholder for predictive maintenance logic.
    description: |
      This component represents the planned integration of Copernicus/forecast data
      to trigger preemptive cleaning and scaling. See /predictive_maintenance/ for details.

