apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edge-cleaner-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-cleaner
  minReplicas: 1
  maxReplicas: 5
  metrics:
    # If you want to use a custom aggregated metric from Cloud Analytics,
    # you can define a custom metric below. For example:
    # - type: Pods
    #   pods:
    #     metric:
    #       name: composite_metric
    #     target:
    #       type: AverageValue
    #       averageValue: 130
    #
    # For now, we'll use the CPU utilization metric:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60

