---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edge-cleaner-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-cleaner
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-cleaner
  labels:
    app: edge-cleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-cleaner
  template:
    metadata:
      labels:
        app: edge-cleaner
    spec:
      containers:
        - name: edge-cleaner
          image: ghcr.io/yourusername/edge-cleaner:latest  # Replace with your actual image
          ports:
            - containerPort: 5000  # Match your application's listening port
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
