AWSTemplateFormatVersion: '2010-09-09'
Description: Secure AWS deployment for AIr4LifeOnTheEdge cloud analytics with NebulOuS integration

Parameters:
  EnvironmentName:
    Description: Environment name prefix for resources
    Type: String
    Default: Air4LifeProd

  AmiId:
    Description: Amazon Linux 2 AMI ID
    Type: AWS::EC2::Image::Id

  KeyName:
    Description: EC2 Key Pair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

  SSHSourceIP:
    Description: Allowed SSH source IP/CIDR (e.g., 123.45.67.89/32)
    Type: String
    Default: 123.45.67.89/32

  VpcCIDR:
    Description: VPC CIDR block (new VPC only)
    Type: String
    Default: 10.192.0.0/16

  ExistingVpcCidr:
    Description: Existing VPC CIDR block (if not creating new)
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCIDR:
    Description: Public subnet CIDR block
    Type: String
    Default: 10.192.10.0/24

  VpcId:
    Description: Existing VPC ID (optional)
    Type: String
    Default: ""

Conditions:
  CreateNewVPC: !Equals [!Ref VpcId, ""]

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Condition: CreateNewVPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !If [CreateNewVPC, !Ref VPC, !Ref VpcId]
      CidrBlock: !Ref PublicSubnetCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicSubnet

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName}-IGW

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !If [CreateNewVPC, !Ref VPC, !Ref VpcId]
      InternetGatewayId: !Ref InternetGateway
    Tags:        # Fixed indentation here
      - Key: Name
        Value: !Sub ${EnvironmentName}-GW-Attachment

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "Security group for ${EnvironmentName} nodes"
      VpcId: !If [CreateNewVPC, !Ref VPC, !Ref VpcId]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHSourceIP
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: !If [CreateNewVPC, !Ref VpcCIDR, !Ref ExistingVpcCidr]  # Fixed line

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AmiId
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          systemctl enable docker
          systemctl start docker
          docker run -d -p 5000:5000 ${DockerImageURI}

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: [!Ref PublicSubnet]
      LaunchConfigurationName: !Ref LaunchConfig
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 1
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Node
          PropagateAtLaunch: true

Outputs:
  VPCId:
    Description: VPC ID
    Value: !If [CreateNewVPC, !Ref VPC, !Ref VpcId]
  PublicSubnet:
    Description: Public subnet ID
    Value: !Ref PublicSubnet
  SecurityGroupId:
    Description: Instance security group ID
    Value: !Ref InstanceSecurityGroup




