# config.yaml
# AIr4LifeOnTheEdge Configuration File (v3.1)
# All values use 0-1 scale unless otherwise noted

mqtt:
  broker: "mqtt://broker.hivemq.com:1883"  # External broker URL
  # Credentials should be set via Kubernetes Secrets
  username: ""  # Leave empty if no authentication
  password: ""  # Leave empty if no authentication

server:
  host: "0.0.0.0"  # Bind to all interfaces
  port: 5000        # Must match Kubernetes Service port

drone:
  ip: "192.168.10.1"        # Tello drone IP (default)
  port: 8889                # Fixed command port
  local_port: 9000          # Local response port

sensor:
  threshold: 0.7            # 0-1 scale (valid range: 0.0-1.0)
  poll_interval: 10         # Seconds (min: 1, max: 3600)
  calibration_factor: 1.0   # Adjust for hardware variance

analytics:
  cloud_report_freq: 5      # Report every N cycles (min: 1)
  dust_risk_threshold: 0.7  # Predictive trigger threshold

predictive:
  cams_api_url: "https://api.ceda.ac.uk/cams-global-reanalysis"
  compensation_factor: 1.25 # Range: 1.0-1.5 (CAMS adjustment)

# Validation schema (for documentation purposes)
# _schema:
#   sensor:
#     threshold:
#       type: float
#       min: 0.0
#       max: 1.0
#     poll_interval:
#       type: integer
#       min: 1
#       max: 3600
