# config.yaml
# AIr4LifeOnTheEdge Configuration

mqtt:
  user: ${MQTT_USER}          # Line 4-5 fix: Environment variable reference
  password: ${MQTT_PASS}      # Instead of hardcoded credentials
  broker: "mqtt://broker.hivemq.com:1883"
  port: 1883
  keepalive: 60

server:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: ${FLASK_SECRET_KEY}

sensor:
  threshold: 0.7              # 0-1 scale
  poll_interval: 10           # Seconds
  calibration_factor: 1.05

analytics:
  cloud_report_freq: 5        # Minutes
  dust_risk_threshold: 0.7    # 0-1 scale
  max_retries: 3

predictive:
  cams_api_url: "https://api.ceda.ac.uk/cams-global-reanalysis"
  compensation_factor: 1.25
  refresh_interval: 3600      # Seconds
