# config.yaml

mqtt:
  broker: "mqtt://broker.hivemq.com:1883"
  username: ""         # Add username if needed
  password: ""         # Add password if needed

server:
  host: "0.0.0.0"
  port: 5000

drone:
  ip: "192.168.10.1"   # Replace with your drone's IP address if applicable
  port: 8889
  local_port: 9000

sensor:
  threshold: 80        # Sensor threshold for triggering actions
