version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: drone_server
    ports:
      - "5000:5000"
    networks:
      - edge_network
    environment:
      - FLASK_DEBUG=false
      - SOILING_THRESHOLD=0.7
      - SENSOR_POLL_INTERVAL=10
      - JWT_SECRET_KEY=development_secret
    command: python server/edge_command_server.py
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  simulation:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sensor_simulation
    command: python simulation/simulate_sensor.py
    environment:
      - SENSOR_POLL_INTERVAL=10
      - SERVER_URL=http://server:5000/start_mission
    depends_on:
      server:
        condition: service_healthy
    networks:
      - edge_network

  redis:
    image: redis:7-alpine
    networks:
      - edge_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s

networks:
  edge_network:
    driver: bridge

volumes:
  redis_data:
