version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: drone_server
    ports:
      - "5000:5000"
    networks:
      - edge_network
    environment:
      - FLASK_DEBUG=false
      - SOILING_THRESHOLD=0.7
      - SENSOR_POLL_INTERVAL=10
    command: python server/edge_command_server.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 60s
      timeout: 10s

  simulation:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sensor_simulation
    command: python simulation/simulate_sensor.py
    environment:
      - SENSOR_POLL_INTERVAL=10
    depends_on:
      server:
        condition: service_healthy
    networks:
      - edge_network
    restart: unless-stopped

networks:
  edge_network:
    driver: bridge
