apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-cleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-cleaner
  template:
    metadata:
      labels:
        app: edge-cleaner
    spec:
      containers:
        - name: edge-cleaner
          image: REPLACE_WITH_YOUR_IMAGE_NAME
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "1Gi"
          env:
            - name: SENSOR_POLL_INTERVAL
              value: "10"
            - name: SOILING_THRESHOLD
              value: "0.7"
            - name: CLOUD_REPORT_FREQ
              value: "5"
          ports:
            - containerPort: 5000

