apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-cleaner
  labels:
    app: air4life-edge
    environment: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: air4life-edge
  template:
    metadata:
      labels:
        app: air4life-edge
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
      containers:
        - name: edge-node
          image: ghcr.io/yourorg/edge-cleaner:1.3.0
          imagePullPolicy: IfNotPresent
          envFrom:  # Indentation fix applied
            - configMapRef:
                name: edge-config
            - secretRef:
                name: edge-secrets
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTPS  # Probe scheme explicitly set to HTTPS
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTPS  # Probe scheme explicitly set to HTTPS
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: edge-service
spec:
  type: ClusterIP
  selector:
    app: air4life-edge
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
