apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-config
  labels:
    app: air4life-edge
data:
  # Base configuration
  SENSOR_POLL_INTERVAL: "10"
  SOILING_THRESHOLD: "0.7"
  CLOUD_REPORT_FREQ: "5"
  
  # Server configuration
  SERVER_PORT: "5000"
  
  # Drone configuration
  DRONE_IP: "192.168.10.1"
  DRONE_PORT: "8889"
  
  # MQTT configuration (credentials handled via Secrets)
  MQTT_BROKER: "mqtt://broker.hivemq.com:1883"
  
  # Analytics configuration
  DUST_RISK_THRESHOLD: "0.7"
  
  # File-based config (alternative approach)
  config.yaml: |
    sensor:
      poll_interval: ${SENSOR_POLL_INTERVAL}
      threshold: ${SOILING_THRESHOLD}
    server:
      port: ${SERVER_PORT}
