apiVersion: v1
kind: Secret
metadata:
  name: edge-secrets
type: Opaque
data:
  # Replace these placeholders with your actual base64-encoded values.
  # For example, to encode a password, run:
  #   echo -n "your_password" | base64
  MQTT_PASSWORD: "<base64_encoded_value>"
  CAMS_API_KEY: "<base64_encoded_value>"
