apiVersion: v1
kind: Secret
metadata:
  name: edge-secrets
  namespace: default
  labels:  # Fixed labels at Line 6
    app: air4life-edge
    environment: production
    tier: backend
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    k8s.v1.metal-stack.io/encrypted: "true"
type: Opaque
data:
  MQTT_USER: YWlyNGxpZmUtdXNlcg==
  MQTT_PASSWORD: c2VjcmV0LXBhc3N3b3JkMTIz
  CAMS_API_KEY: Y2Ftc19hcGlfa2V5XzEyMzQ1Ng==
  FLASK_SECRET_KEY: Zmxhc2stc2VjcmV0LWtleQ==
  JWT_SECRET_KEY: <base64-encoded-256-bit-secret>  # Placeholder remains for your secure key
stringData:
  LOG_LEVEL: "INFO"
