apiVersion: v1
kind: Secret
metadata:
  name: edge-secrets
  namespace: default
  labels:
    app: air4life-edge
    environment: production
    tier: backend
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    k8s.v1.metal-stack.io/encrypted: "true"
type: Opaque
data:
  # Example values (generate with: echo -n "value" | base64)
  MQTT_USER: "YWlyNGxpZmUtdXNlcg=="          # air4life-user
  MQTT_PASSWORD: "c2VjcmV0LXBhc3N3b3JkMTIz"  # secret-password123
  CAMS_API_KEY: "Y2Ftc19hcGlfa2V5XzEyMzQ1Ng=="  # cams_api_key_123456
  JWT_SECRET_KEY: "ZjAwZjM3MjgtY2QwZC00ODU5LTkzYjYtZWNhYjFiYWM5YjQw"  # Random 256-bit key
  FLASK_SECRET_KEY: "Zmxhc2stc2VjcmV0LWtleQ=="  # flask-secret-key

stringData:
  LOG_LEVEL: "INFO"
