apiVersion: v1
kind: Secret
metadata:
  name: edge-secrets
  namespace: default
  labels:
    app: air4life-edge
    tier: production
    component: security
  annotations:
    k8s.v1.metal-stack.io/encrypted: "true"  # If using KMS encryption
    sealedsecrets.bitnami.com/cluster-wide: "true"  # For sealed secrets
type: Opaque
data:
  # Base64 encoded values (generate with: echo -n "value" | base64)
  MQTT_USER: "YWlyNGxpZmUtdXNlcg=="          # air4life-user
  MQTT_PASSWORD: "c2VjcmV0LXBhc3N3b3JkMTIz"  # secret-password123
  CAMS_API_KEY: "Y2Ftc19hcGlfa2V5XzEyMzQ1Ng=="  # cams_api_key_123456
  FLASK_SECRET_KEY: "Zmxhc2stc2VjcmV0LWtleQ=="  # flask-secret-key

stringData:  # For non-sensitive configuration (not recommended for secrets)
  LOG_LEVEL: "INFO"
