apiVersion: v1
kind: Secret
metadata:
  name: edge-secrets
  namespace: default
  labels:
    app: air4life-edge
    environment: production
    tier: backend
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    k8s.v1.metal-stack.io/encrypted: "true"
type: Opaque
data:
  MQTT_USER: "dXNlcm5hbWU="              # Decodes to "username" [2]
  MQTT_PASSWORD: "c2VjcmV0LXBhc3N3b3Jk"  # Decodes to "secret-password" [2]
  CAMS_API_KEY: "Y2Ftc19hcGlfa2V5"       # Decodes to "cams_api_key" [2]
  FLASK_SECRET_KEY: "Zmxhc2stc2VjcmV0"   # Decodes to "flask-secret" [2]

stringData:
  LOG_LEVEL: "INFO"
